---
config:
  address: 10.58.0.30   # TODO make a parameter

env:
  cp_enable: "true"
  vip_arp: "true"
  vip_leaderelection: "true"

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    # cpu: 21m
    memory: 105M
