---
bases:
  - ../../../clusters/environments.yaml

apiVersions:
  - monitoring.coreos.com/v1

releases:
  - name: traefik
    chart: oci://ghcr.io/traefik/helm/traefik
    version: 39.0.1
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - values.yaml
      - values.yaml.gotmpl
