---
apiVersions:
  - monitoring.coreos.com/v1
repositories:
  - name: traefik
    url: https://traefik.github.io/charts/
releases:
  - name: traefik
    chart: traefik/traefik
    version: 38.0.2
    values:
      - values.yaml
    namespace: '{{ (readFile "app.yaml" | fromYaml).appNamespace }}'
