---
controller:
  enabled: true

speaker:
  enabled: true

crds:
  enabled: true

# Native MetalLB configuration
configInline:
  address-pools:
    - name: lan-pool
      protocol: layer2
      addresses:
        - {{.Values.network.metallb.poolCIDR}}
