---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts/
releases:
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 80.14.4
    values:
      - ../../../settings/common.yaml
      - values.yaml
      - externalsecret.yaml
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
