---
image:
  # -- multus installer tag
  repository: ghcr.io/k8snetworkplumbingwg/multus-cni
  tag: v4.2.3-thick@sha256:e93af9e533cc16ca7847aeec3b516c9b1e8891c2b95c727991e94c9b59c4970e

cni:
  image:
    repository: rancher/hardened-cni-plugins
    tag: v1.9.0

  paths:
    bin: /var/lib/rancher/k3s/data/cni
    config: /var/lib/rancher/k3s/agent/etc/cni/net.d

  logLevel: debug
