---
# Default values for cloudflare-tunnel-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudflare:
  secretRef:
    name: cloudflare-tunnel-secret
    accountIDKey: accountID
    tunnelNameKey: tunnelName
    apiTokenKey: apiToken

ingressClass:
  name: cloudflare-tunnel
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
  isDefaultClass: false

replicaCount: 2

resources:
  limits:
    cpu: null

image:
  repository: cr.strrl.dev/strrl/cloudflare-tunnel-ingress-controller
  tag: 0.0.21

cloudflared:
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: 2026.1.1@sha256:5bb6a0870686742d00e171f36c892ba91e5994631bc363d808b9ba822262dad6
  replicaCount: 2

cloudflaredServiceMonitor:
  create: true
#   jobLabel: ""
#   interval: ""
#   scrapeTimeout: ""
#   honorLabels: false
#   metricRelabelings: []
#   relabelings: []
#   labels: {}
#   scheme: http
