# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: bjw-s-labs
    url: https://bjw-s-labs.github.io/helm-charts

releases:
  - name: esphome
    chart: bjw-s-labs/app-template
    version: 4.6.2
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - values.yaml
      - values.yaml.gotmpl
      - externalsecret.yaml
